#!/usr/bin/env bash
# this installs nginx and also configures it on a remote server

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello world!' > /var/www/html/index.nginx-debian.html
service nginx start
